-- Supabase Sohbet Odası Kurulum Scripti
-- Bu kodu Supabase Dashboard -> SQL Editor kısmına yapıştırıp "Run" tuşuna basın.

-- 1. Mesajlar tablosunu oluştur
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    content TEXT NOT NULL,
    username TEXT NOT NULL,
    channel_name TEXT DEFAULT 'sohbet'
);

-- 2. Realtime (Anlık Güncelleme) özelliğini mesajlar tablosu için aktif et
-- Not: Eğer bu tablo zaten yayında/yayındaysa hata verebilir, bu normaldir.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'messages'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
    END IF;
END $$;

-- 3. RLS (Row Level Security) Ayarları
-- RLS'yi aktif et
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Okuma izni: Herkes mesajları okuyabilir
DROP POLICY IF EXISTS "Herkes okuyabilir" ON public.messages;
CREATE POLICY "Herkes okuyabilir" ON public.messages
    FOR SELECT USING (true);

-- Yazma izni: Herkes mesaj gönderebilir (Anonim erişim açıksa)
DROP POLICY IF EXISTS "Herkes ekleyebilir" ON public.messages;
CREATE POLICY "Herkes ekleyebilir" ON public.messages
    FOR INSERT WITH CHECK (true);
